[package]
name = "rust_raytracer"
version = "0.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mimalloc = { version = "0.1", default-features = false }
ultraviolet = "0.10"
minifb = "0.28"
fastrand = "2.3"
quasirandom = "0.3"
rayon = "1.10"
radiant = "0.3"
clap = { version = "4.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.10"
png = "0.17"
tobj = "4.0"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"
debug = true
