[package]
name = "rust_raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mimalloc = { version = "0.1.17", default-features = false }
minifb = "0.23"
fastrand = "1.8.0"
rayon = "1.6.1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
emit = "asm"